name: Node CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ node-version }}
    - name: "Cached Elm 0.19.1"
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-elm-0-19-1
    - name: install elm and elm-test
      run: |
        echo '{"scripts":{"test":"elm-test"},"dependencies":{"elm":"^0.19.1-3","elm-test":"^0.19.1-revision2"}}' > package.json
        npm i       
    - name: run elm-test
      run: ./node_modules/elm-test/bin/elm-test
      env:
        CI: true